ARG RUST_IMAGE=rust:1.95.0-bookworm
ARG PYTHON_IMAGE=python:3.11.13-slim-bookworm
ARG BEDGRAPH_TO_BIGWIG_URL=https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedGraphToBigWig
ARG BEDGRAPH_TO_BIGWIG_SHA256=1a1527cf364e1e572a81c7284fc9ccd2b3690b5896baa5b57399864f85ad7771

FROM ${RUST_IMAGE} AS gtg-builder

ARG GTG_COMMIT=e12aca6b49ee7208952467db4a2a9e2f79b98efb

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        build-essential \
        ca-certificates \
        clang \
        cmake \
        git \
        libbz2-dev \
        libclang-dev \
        libcurl4-openssl-dev \
        liblzma-dev \
        libssl-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --filter=blob:none \
        https://github.com/Platinum-Pedigree-Consortium/Platinum-Pedigree-Inheritance.git \
        /build/gtg \
    && git -C /build/gtg checkout --detach "${GTG_COMMIT}"

COPY containers/gtg.Cargo.lock /build/gtg/code/rust/Cargo.lock

RUN cargo build \
      --manifest-path /build/gtg/code/rust/Cargo.toml \
      --locked \
      --release \
      --bin gtg-ped-map \
      --bin gtg-concordance


FROM ${PYTHON_IMAGE} AS runtime

ARG GTG_COMMIT=e12aca6b49ee7208952467db4a2a9e2f79b98efb
ARG BEDGRAPH_TO_BIGWIG_URL
ARG BEDGRAPH_TO_BIGWIG_SHA256
LABEL org.opencontainers.image.source="https://github.com/quinlan-lab/tapestry"
LABEL org.opencontainers.image.description="Tapestry generic pedigree/model-only runtime"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.gtg.commit="${GTG_COMMIT}"
LABEL org.opencontainers.image.ucsc-bedGraphToBigWig.sha256="${BEDGRAPH_TO_BIGWIG_SHA256}"

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        bcftools \
        ca-certificates \
        curl \
        libbz2-1.0 \
        libcurl4 \
        liblzma5 \
        procps \
        tabix \
        zlib1g \
    && rm -rf /var/lib/apt/lists/*

# Retain the legacy UCSC generator as a pinned parity oracle for the pyBigWig
# migration test. Production BigWigs are generated by pyBigWig.
RUN curl --fail --location --output /usr/local/bin/bedGraphToBigWig \
        "${BEDGRAPH_TO_BIGWIG_URL}" \
    && echo "${BEDGRAPH_TO_BIGWIG_SHA256}  /usr/local/bin/bedGraphToBigWig" \
        | sha256sum --check --strict \
    && chmod 0755 /usr/local/bin/bedGraphToBigWig

COPY requirements-pipeline.txt /opt/tapestry/requirements-pipeline.txt
RUN python -m pip install --no-cache-dir \
      --requirement /opt/tapestry/requirements-pipeline.txt

COPY --from=gtg-builder /build/gtg/code/rust/target/release/gtg-ped-map /usr/local/bin/gtg-ped-map
COPY --from=gtg-builder /build/gtg/code/rust/target/release/gtg-concordance /usr/local/bin/gtg-concordance
COPY src /opt/tapestry/src

ENV PYTHONPATH=/opt/tapestry/src:/opt/tapestry/src/util

RUN gtg-ped-map --version \
    && gtg-concordance --version \
    && test -x /usr/local/bin/bedGraphToBigWig \
    && bcftools --version \
    && python /opt/tapestry/src/tapestry_validate.py --help \
    && python /opt/tapestry/src/filter_model_beds.py --help \
    && python /opt/tapestry/src/normalize_joint_vcf.py --help \
    && python /opt/tapestry/src/run_gtg_inheritance.py --help \
    && python /opt/tapestry/src/capture_versions.py --help \
    && python /opt/tapestry/src/generate_reference_cpgs.py --help \
    && python /opt/tapestry/src/phase_meth_to_founder_haps.py --help \
    && python /opt/tapestry/src/expand_model_to_all_cpgs.py --help \
    && python /opt/tapestry/src/write_results_manifest.py --help

WORKDIR /work
