"""Tapestry wiki figure generator.

Each page is produced by a `page_*` function that writes its narrative
`*.md` and figure assets into its own folder under `wiki/`. The function
for a given page is the single source of truth for that page; markdown
is written from inside the function so the prose and the figure
filenames stay in lockstep.

Run:
    python wiki/generate_wiki.py                     # all pages
    python wiki/generate_wiki.py --page motivation   # one page

The vendored `pedigree_wise_workflow/inheritance_mapping/` section is
*not* regenerated by this script — see that folder's README.md for the
sync procedure.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _helpers import head_sha, permalink  # noqa: F401  (permalink reserved for later pages)

WIKI_DIR = Path(__file__).resolve().parent
SHA = head_sha()
sys.path.insert(0, str(WIKI_DIR))

from motivation import single_indiv_phasing, trio_discovery  # noqa: E402
from pedigree_wise_workflow.founder_phased_methylation import (  # noqa: E402
    founder_phased_methylation,
)


# ---------------------------------------------------------------------------
# Page: motivation (shared between pedigree-wise and trio-wise workflows)
# ---------------------------------------------------------------------------

MOTIVATION_MD = """\
# Why phase DNA methylation?

This page is part of the [tapestry wiki](../README.md). It motivates
the rest of the wiki by answering one question: *why is it worth
phasing per-CpG methylation onto each haplotype, instead of leaving it
as a single number per CpG?* Two pairs of cartoon figures build the
answer on a small synthetic locus: the first pair takes a single
individual through a before/after of phasing to show what the read
partition does to the methylation profile; the second pair places that
individual into a trio so the two flagship use cases — *de novo
epimutations* and *compound genetic-epigenetic heterozygotes* — fall
out directly, together with the polars query a user runs against
tapestry's BED output to surface each one.

## Definitions

- **De novo epimutation** — a change in the methylation state of a
  specific physical homolog across a single meiosis. Detectable only
  when a parent and child can be compared on the *same* haplotype,
  which in turn requires phased methylation.
- **Compound genetic-epigenetic heterozygote** — an individual who
  inherits two different parental haplotypes such that one carries a
  genetic variant and the other carries an aberrant methylation state
  in *trans*. Invisible to either an unphased genotype call or an
  unphased methylation call, but detectable directly from per-haplotype
  tracks plus a trio.

## Single individual: before vs. after phasing

![Before phasing](single_indiv_before_phasing.png)

A small synthetic locus with mixed SNVs and CpGs. Ten ragged reads
cover overlapping windows; each read is one monospace row carrying a
`0`/`1` glyph at SNV columns and a small **red** (unmethylated) /
**blue** (methylated) box at CpG columns. Above the pile-up, a single
gray bigwig-style methylation track reports the *pooled* per-CpG
methylation level. With reads unpartitioned, the two haplotypes'
methylation states get averaged into one number per CpG — so per-CpG
heterozygous methylation is hidden inside an intermediate value.

![After phasing](single_indiv_after_phasing.png)

The same ten reads, now partitioned by haplotype: rows are grouped
paternal-above-maternal (one `Pat hap` / `Mat hap` label per group on
the left) and the SNV bits themselves carry the partition. With the
partition in hand, the pooled profile splits into two stacked
per-haplotype bigwig tracks. What Figure 2 shows is what tapestry computes mechanically for
every CpG once the haplotype partition is in hand. The two payoffs of
having those per-haplotype profiles only become visible once the
individual is placed into a pedigree.

## Trio use case 1: de novo epimutation

![Trio de novo](trio_denovo.svg)

The kid, now in a trio. Each individual carries two haplotypes drawn
as horizontal coloured bars; each bar is decorated with methylation
lollipops at CpG positions (filled = methylated, open = unmethylated).
At the right CpG cluster, two de novo events sit on opposite
parental haplotypes. The kid's paternal homolog (`A`, inherited from
dad) is methylated there, but dad's same physical homolog is
unmethylated — a de novo *gain* of methylation. Symmetrically, the
kid's maternal homolog (`C`, inherited from mom) is unmethylated at
the same cluster, but mom's same physical homolog is methylated — a
de novo *loss*. The left cluster is concordant on both sides
(unmethylated on `A` from dad to kid; methylated on `C` from mom to
kid).

![Trio de novo BED + polars](trio_denovo_bed.png)

Once tapestry produces a per-CpG haplotype-resolved BED, surfacing
the de novo gain of methylation on the kid's paternal hap is a
one-pass polars filter: pick the dad haplotype that was transmitted
to the kid (using the `pat_hap` phasing column), then keep CpGs where
`kid_pat - dad_transmitted` is *positive* on average over a small
window. Mirror the filter sign to surface a de novo *loss*; mirror
both the column choice (`mat_hap`/`mom_C`/`mom_D`) and the sign to
surface either de novo direction on the maternal side.

## Trio use case 2: compound genetic-epigenetic heterozygote

![Trio compound het](trio_compound_het.svg)

Same trio, different scenario: the kid inherits **dad's hap A** —
which carries a SNV variant (red star) — *and* **mom's hap C** —
which carries an aberrantly hyper-methylated promoter region (filled
lollipops at the leftmost three CpGs). The two hits sit on opposite
parental haplotypes, so the kid is a compound genetic-epigenetic
heterozygote *in trans* — silenced on the maternal allele by aberrant
methylation, broken on the paternal allele by a coding variant. Each
parent is a silent carrier of one of the two hits.

![Trio compound het BED + polars](trio_compound_het_bed.png)

Discovery from tapestry's BED is again a polars chain over two
inputs: a per-CpG methylation table and a per-SNV genotype table,
both with one column per parental haplotype (`dad_A`, `dad_B`,
`mom_C`, `mom_D`) plus the kid's per-side phased values
(`kid_pat`, `kid_mat`) and the phasing labels (`pat_hap`, `mat_hap`).
Step 1 finds methylation-outlier regions where exactly one parental
hap is the outlier and the kid inherits that hap with ~unchanged
meth. Step 2 finds genotype-outlier SNVs with the analogous
inheritance check. Step 3 joins the two and keeps loci where the
meth-outlier and geno-outlier come from *different* parents — i.e.,
the two hits are in trans.

## What's next

The rest of the wiki is concerned with how tapestry actually performs
the phasing summarised above:

- The [pedigree-wise workflow](../pedigree_wise_workflow/index.md)
  combines hiphase's read-backed phasing with `gtg-ped-map` /
  `gtg-concordance`'s inheritance-based phasing across a full
  pedigree, labelling each measurement with a founder haplotype.
- The [trio-wise workflow](../trio_wise_workflow/index.md) uses
  whatshap / pedMEC trio phasing to label each measurement with one
  of the parents' haplotypes — an option for the trio-only setting.
"""


def page_motivation(outdir: Path) -> None:
    page_dir = outdir / "motivation"
    page_dir.mkdir(parents=True, exist_ok=True)
    single_indiv_phasing.main()
    trio_discovery.main()
    md_path = page_dir / "motivation.md"
    md_path.write_text(MOTIVATION_MD)
    print(f"[wiki] Wrote {md_path}")


# ---------------------------------------------------------------------------
# Page: founder-phased methylation (Step 3)
# ---------------------------------------------------------------------------

FOUNDER_PHASED_METHYLATION_MD = f"""\
# Founder-phased methylation (Step 3)

This page is part of the
[pedigree-wise workflow](../index.md). It covers Step 3 of the
pipeline — `phase_meth_to_founder_haps.py` and `hap_map_pedigree.py` —
which is the conceptual centre of tapestry. Step 3 takes the two
phasings produced upstream and uses them to relabel each per-CpG
methylation measurement with one of the four founder homologs of
the pedigree.

## The two phasings, and where they meet

Two independent phasings reach Step 3:

- **Read-backed phasing** (Step 1A, hiphase). Within each *phase
  block*, hiphase emits two anonymous read partitions, `hap1` and
  `hap2`, and writes the partition into the BAM (`HP`/`PS` tags).
  Inside a block the two partitions are linked across heterozygous
  sites; across blocks the partition labels are independent.
- **Inheritance-based phasing** (Step 1B, `gtg-ped-map` +
  `gtg-concordance`). Within each *linkage block* (also called an
  inheritance block), inheritance-based phasing reaches Step 3 as
  two parallel data structures:
  - The **iht-phased VCF**, which phases each het variant as `p|m`
    where `p` is the allele on the paternal homolog and `m` the
    allele on the maternal homolog. Tapestry parses this in
    [`get_iht_phasing`]({permalink('src/phasing_pedigree.py', 99, SHA)}).
  - The **iht-blocks map**, which assigns one of the founder-haplotype
    letters (`A`/`B` for dad's two homologs, `C`/`D` for mom's, etc.)
    to the paternal and maternal slot in each block. Within a block,
    these letters are fixed; they are *not* fixed across blocks (a
    crossover changes which dad letter sits in the paternal slot).
    Tapestry parses this in
    [`get_iht_blocks`]({permalink('src/phasing_pedigree.py', 153, SHA)}).

The two block partitions of the genome do not align. The natural
unit on which to relate them is the **hap-map block**: the
intersection of one read-backed phase block with one linkage block.
Inside such an intersection the read partition is consistent and
the founder labels are fixed, so a single decision relates one to
the other.

## Bit-vector match

Inside one hap-map block, each het SNV contributes one bit to three
parallel vectors:

- `hap1` — the read-partition allele on hiphase's `hap1` side.
- `pat` — the allele on the paternal founder homolog.
- `mat` — the allele on the maternal founder homolog.

![Bit-vector match](bit_vector_match.png)

`hap1` is compared against `pat` and `mat` in turn. Since every
contributing site is heterozygous, `pat` and `mat` carry opposite
alleles at each site; consequently the per-site match is mutually
exclusive, and `concordance(hap1, pat) + concordance(hap1, mat) = 1`
exactly. The decision is a single threshold:

- If `concordance(hap1, pat) > 0.5` → hiphase's `hap1` reads descend
  from the paternal founder homolog (and `hap2` reads from the
  maternal one).
- Otherwise → the assignment is flipped.

This decision is made once per hap-map block; the relevant code is
the bit-vector comparison in [`get_hap_map`]({permalink('src/hap_map_pedigree.py', 13, SHA)}),
specifically the `similarity_hap1_pat > 0.5` branch at
[line 58]({permalink('src/hap_map_pedigree.py', 58, SHA)}).

## Mechanical re-bucketing of methylation

Once each haplotagged read carries a founder tag, the per-CpG
methylation summaries split mechanically. Reads bucketed under the
HP tag's `hap1` and `hap2` files are re-emitted as `pat` and `mat`
files (or vice versa) according to the decision above; per-CpG
methylation levels follow the bucket rather than being recomputed.
The assembly is performed in
[`phase_meth_to_founder_haps`]({permalink('src/phase_meth_to_founder_haps.py', 44, SHA)}).

## Mismatch sites and Step 4 QC

Most hap-map blocks have a small number of sites where `hap1`
disagrees with the chosen parental vector — concordance < 1. Those
sites are recorded alongside the hap-map block and propagated to
Step 4 ([all-CpG expansion](../all_cpg_expansion/all_cpg_expansion.md)),
where every CpG within 50 bp of one of them is annotated with the
`cpg_is_within_50bp_of_mismatch_site` QC flag in tapestry's BED
output. Downstream consumers can choose whether to keep or filter
those CpGs.
"""


def page_founder_phased_methylation(outdir: Path) -> None:
    page_dir = outdir / "pedigree_wise_workflow" / "founder_phased_methylation"
    page_dir.mkdir(parents=True, exist_ok=True)
    founder_phased_methylation.main()
    md_path = page_dir / "founder_phased_methylation.md"
    md_path.write_text(FOUNDER_PHASED_METHYLATION_MD)
    print(f"[wiki] Wrote {md_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

PAGES = {
    "motivation": page_motivation,
    "founder_phased_methylation": page_founder_phased_methylation,
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--page", choices=sorted(PAGES.keys()),
        help="Render only one page (default: render every page).",
    )
    parser.add_argument(
        "--outdir", type=Path, default=WIKI_DIR,
        help="Directory to write the wiki into.",
    )
    args = parser.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    targets = [PAGES[args.page]] if args.page else list(PAGES.values())
    for fn in targets:
        fn(args.outdir)


if __name__ == "__main__":
    main()
