"""
Tapestry wiki figure generator.

Each page is produced by a `page_*` function that writes both the
narrative `*.md` and the `fig*.png` bundle into its own folder under
`wiki/`. The function for a given page is the single source of truth
for that page; markdown is written from inside the function so the
prose and the figure constants stay in lockstep.

Run:
    python wiki/generate_wiki.py                     # all pages
    python wiki/generate_wiki.py --page motivation   # one page

The vendored `pedigree_wise_workflow/inheritance_mapping/` section is
*not* regenerated by this script — see that folder's README.md for the
sync procedure.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.patches import FancyArrowPatch, Rectangle

from _helpers import draw_methylation_bars, head_sha, permalink

WIKI_DIR = Path(__file__).resolve().parent
SHA = head_sha()


# ---------------------------------------------------------------------------
# Page: motivation (shared between pedigree-wise and trio-wise workflows)
# ---------------------------------------------------------------------------
#
# Spec: claude_plan.md §11.
#
# Two cartoon figures, both fully synthetic. Toy details are baked in here
# (no RNG); see §11.3 for the rationale.

# --- Toy setup (§11.3) -----------------------------------------------------

# Genomic-axis positions of the four marked sites.
# CpG1 sits immediately to the right of SNV1 (so the compound-het framing
# is visually obvious); CpG2 sits in the middle of the locus with no adjacent
# SNV (so it is a pure methylation phenomenon, not tied to a local genotype).
SNV1_X = 0.05
CPG1_X = 0.18
CPG2_X = 0.55
SNV2_X = 0.92
SITE_X = (SNV1_X, CPG1_X, CPG2_X, SNV2_X)
SITE_LABELS = ("SNV1", "CpG1", "CpG2", "SNV2")

READ_X_START = -0.02
READ_X_END = 1.02

N_PAT = 6
N_MAT = 6
N_READS = N_PAT + N_MAT

# Per-haplotype glyphs at each of the four marked sites:
#   paternal: SNV1=0, CpG1=○ (unmethylated), CpG2=● (methylated), SNV2=0
#   maternal: SNV1=1, CpG1=● (methylated),   CpG2=○ (unmethylated), SNV2=1
PAT_GLYPHS = ("0", "○", "●", "0")
MAT_GLYPHS = ("1", "●", "○", "1")

# Colour convention used everywhere in the wiki (matches §13 / hero cartoon).
COLOR_PAT = "#1f77b4"   # blue
COLOR_MAT = "#d62728"   # red
COLOR_NEUTRAL = "#7f7f7f"  # uniform grey for the unphased "before" pileup

GLYPH_FONTSIZE = 11
RULER_FONTSIZE = 10


def _draw_ruler(ax: plt.Axes, ruler_y: float, label_y: float) -> None:
    """Reference-genome ruler with the four marked positions.

    `ruler_y` is the y-coordinate of the horizontal ruler line; `label_y`
    is where the SNV/CpG text labels sit. Both are caller-supplied so the
    ruler can be positioned above an inverted-y read pileup.
    """
    ax.plot([READ_X_START, READ_X_END], [ruler_y, ruler_y],
            color="black", linewidth=0.8)
    tick_dy = 0.10 if ruler_y < label_y else -0.10
    for x, label in zip(SITE_X, SITE_LABELS):
        ax.plot([x, x], [ruler_y, ruler_y + tick_dy * 0.45],
                color="black", linewidth=0.8)
        ax.text(x, label_y, label, ha="center", va="bottom",
                fontsize=RULER_FONTSIZE, family="monospace")


def _draw_read(
    ax: plt.Axes,
    y: float,
    color: str,
    glyphs: tuple[str, str, str, str],
    height: float = 0.55,
) -> None:
    """One read bar with site glyphs overlaid at the four marked positions."""
    ax.add_patch(
        Rectangle(
            (READ_X_START, y - height / 2),
            READ_X_END - READ_X_START,
            height,
            facecolor=color, edgecolor="black", linewidth=0.4, alpha=0.55,
        )
    )
    for x, g in zip(SITE_X, glyphs):
        ax.text(x, y, g, ha="center", va="center",
                fontsize=GLYPH_FONTSIZE, family="monospace",
                fontweight="bold")


RULER_TOP_PAD = 1.6  # rows of vertical headroom above the first read for the ruler
SIDE_LABEL_PAD = 0.18  # extra x-axis margin on the left for "paternal reads" labels


def _setup_pileup_axes(ax: plt.Axes, n_reads: int, with_side_labels: bool = False) -> None:
    left = READ_X_START - (SIDE_LABEL_PAD if with_side_labels else 0.03)
    ax.set_xlim(left, READ_X_END + 0.03)
    ax.set_ylim(-RULER_TOP_PAD, n_reads - 0.5)
    ax.invert_yaxis()
    ax.set_axis_off()


# --- Figure 1: "before" — unphased --------------------------------------

def _render_fig1_before(out_path: Path) -> None:
    """
    Figure 1 of the motivation page (§11.1):
        - Reference ruler (SNV1, CpG1, CpG2, SNV2, left-to-right)
        - 12 uniform-colour read bars, glyphs at each marked site
        - Bar plot (right of the pileup) showing the two CpGs' unphased
          methylation levels, both at 50 % on the shared 0–100 % y-axis.
    """
    fig = plt.figure(figsize=(11, 5.4))
    gs = GridSpec(
        nrows=1, ncols=2,
        width_ratios=(4.0, 1.0),
        wspace=0.18,
        left=0.05, right=0.97, top=0.88, bottom=0.10,
    )

    ax_pileup = fig.add_subplot(gs[0, 0])
    ax_bars = fig.add_subplot(gs[0, 1])

    # Pileup: interleave pat/mat so the "before" picture does not visually
    # pre-suggest the haplotype split.
    glyphs_per_read = []
    for i in range(N_READS):
        glyphs_per_read.append(PAT_GLYPHS if i % 2 == 0 else MAT_GLYPHS)

    _setup_pileup_axes(ax_pileup, N_READS)
    # Ruler line above the first read (recall axis is inverted, so smaller
    # y is higher on the page).
    _draw_ruler(ax_pileup, ruler_y=-0.7, label_y=-1.45)
    for i, glyphs in enumerate(glyphs_per_read):
        _draw_read(ax_pileup, y=i, color=COLOR_NEUTRAL, glyphs=glyphs)

    ax_pileup.set_title(
        "Unphased read pileup at a small locus",
        fontsize=11, pad=14,
    )

    # Bar plot — both CpGs come out at exactly 50 % when methylation is
    # pooled across all 12 reads.
    n_pat = N_PAT
    n_mat = N_MAT
    n_total = n_pat + n_mat
    cpg1_methylated = n_mat            # CpG1: pat reads ○, mat reads ●
    cpg2_methylated = n_pat            # CpG2: pat reads ●, mat reads ○
    fractions = (cpg1_methylated / n_total, cpg2_methylated / n_total)
    draw_methylation_bars(
        ax_bars,
        labels=("CpG1\n(unphased)", "CpG2\n(unphased)"),
        fractions=fractions,
        colors=(COLOR_NEUTRAL, COLOR_NEUTRAL),
        title="Pooled methylation",
    )

    fig.suptitle(
        "Figure 1 — \"Before\": one averaged methylation number per CpG",
        fontsize=13, y=0.98,
    )
    fig.text(
        0.05, 0.02,
        "Both bars come out at 50 %: a single per-CpG number cannot tell "
        "two haplotypes apart.",
        fontsize=9, style="italic",
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=180)
    plt.close(fig)
    print(f"[wiki] Wrote {out_path}")


# --- Figure 2: "after" — phased -----------------------------------------

# Panel C zoomed-out profile (§11.3): 30 CpGs total, two binary tracks.
# Most positions: both haplotypes methylated (●). A handful of common
# unmethylated positions (so the profile isn't visually monotonous), plus
# the two divergent CpGs at indices 5 (CpG1) and 22 (CpG2).
PANEL_C_N = 30
PANEL_C_COMMON_UNMETHYLATED = {3, 11, 18, 27}
PANEL_C_CPG1_IDX = 5
PANEL_C_CPG2_IDX = 22


def _panel_c_tracks() -> tuple[list[str], list[str], list[str]]:
    """Return (paternal_track, maternal_track, dad_paternal_track) glyphs."""
    pat = []
    mat = []
    dad_pat = []
    for i in range(PANEL_C_N):
        if i in PANEL_C_COMMON_UNMETHYLATED:
            pat.append("○"); mat.append("○"); dad_pat.append("○")
        elif i == PANEL_C_CPG1_IDX:
            pat.append("○"); mat.append("●"); dad_pat.append("○")
        elif i == PANEL_C_CPG2_IDX:
            # Epimutation: the child's paternal homolog is methylated at
            # CpG2, but dad's same physical homolog is *not*. So pat=●,
            # dad_pat=○ — one position difference between child and parent
            # on the same physical homolog.
            pat.append("●"); mat.append("○"); dad_pat.append("○")
        else:
            pat.append("●"); mat.append("●"); dad_pat.append("●")
    return pat, mat, dad_pat


def _render_fig2_after(out_path: Path) -> None:
    """
    Figure 2 of the motivation page (§11.2):
        Panel A — same 12 reads, partitioned by haplotype (pat above mat).
        Panel B — four bars: CpG1 pat=0, CpG1 mat=100, CpG2 pat=100, CpG2 mat=0.
        Panel C — zoomed-out profile across ~30 CpGs, two tracks (pat above
                  mat). CpG1 annotated as a compound genetic-epigenetic het;
                  CpG2 annotated as an epimutation, with a small inset
                  comparing dad's pat track to the child's pat track at CpG2.
    """
    fig = plt.figure(figsize=(13.0, 13.5))
    gs = GridSpec(
        nrows=3, ncols=2,
        width_ratios=(2.0, 1.4),
        height_ratios=(1.5, 1.0, 1.7),
        hspace=0.55, wspace=0.22,
        left=0.06, right=0.97, top=0.94, bottom=0.04,
    )

    # ---- Panel A: regrouped, coloured pileup --------------------------------
    ax_a = fig.add_subplot(gs[0, :])
    _setup_pileup_axes(ax_a, N_READS, with_side_labels=True)
    _draw_ruler(ax_a, ruler_y=-0.7, label_y=-1.45)

    # Pat above mat, with a faint divider.
    for i in range(N_PAT):
        _draw_read(ax_a, y=i, color=COLOR_PAT, glyphs=PAT_GLYPHS)
    for j in range(N_MAT):
        _draw_read(ax_a, y=N_PAT + j, color=COLOR_MAT, glyphs=MAT_GLYPHS)
    ax_a.axhline(N_PAT - 0.5, color="black", linewidth=0.6,
                 linestyle=(0, (3, 3)), alpha=0.4)

    # Side labels for the two haplotype groups.
    label_x = READ_X_START - 0.04
    ax_a.text(label_x, (N_PAT - 1) / 2.0,
              "paternal\nreads", ha="right", va="center",
              fontsize=9, color=COLOR_PAT, fontweight="bold")
    ax_a.text(label_x, N_PAT + (N_MAT - 1) / 2.0,
              "maternal\nreads", ha="right", va="center",
              fontsize=9, color=COLOR_MAT, fontweight="bold")
    ax_a.set_title(
        "Panel A — same reads, partitioned by haplotype "
        "(SNVs jointly anchor the assignment)",
        fontsize=11, pad=14,
    )

    # ---- Panel B: prose (left) + four bars (right) on shared 0–100 % y-axis -
    ax_b_text = fig.add_subplot(gs[1, 0])
    ax_b_text.set_axis_off()
    ax_b_text.text(
        0.0, 0.95, "Panel B — phased per-haplotype methylation",
        fontsize=11, fontweight="bold",
        ha="left", va="top", transform=ax_b_text.transAxes,
    )
    ax_b_text.text(
        0.0, 0.78,
        "Each CpG's flat 50 % bar from Figure 1 was hiding a\n"
        "0 % vs 100 % split between the two haplotypes —\n"
        "and the two CpGs split in opposite directions:",
        fontsize=10, ha="left", va="top",
        transform=ax_b_text.transAxes,
    )
    ax_b_text.text(
        0.04, 0.45,
        "CpG1:  pat = 0 %     mat = 100 %\n"
        "CpG2:  pat = 100 %   mat = 0 %",
        fontsize=10, ha="left", va="top", family="monospace",
        transform=ax_b_text.transAxes,
    )
    ax_b_text.text(
        0.0, 0.20,
        "Bars sit on the same 0–100 % y-axis as Figure 1, so the\n"
        "collapse of one tall pooled bar into a pair of extreme\n"
        "phased bars is visually direct when read side-by-side.",
        fontsize=9, ha="left", va="top", style="italic",
        transform=ax_b_text.transAxes,
    )

    ax_b = fig.add_subplot(gs[1, 1])
    draw_methylation_bars(
        ax_b,
        labels=("CpG1\npat", "CpG1\nmat", "CpG2\npat", "CpG2\nmat"),
        fractions=(0.0, 1.0, 1.0, 0.0),
        colors=(COLOR_PAT, COLOR_MAT, COLOR_PAT, COLOR_MAT),
    )

    # ---- Panel C: zoomed-out profile (left) + dad-inset (right) -------------
    ax_c = fig.add_subplot(gs[2, 0])
    pat_track, mat_track, dad_pat_track = _panel_c_tracks()

    # Profile layout: y=1 paternal track, y=0 maternal track, with extra
    # vertical headroom above for the CpG2 callout and below for the CpG1
    # callout.
    ax_c.set_xlim(-2.5, PANEL_C_N - 0.5)
    ax_c.set_ylim(-3.6, 3.4)
    ax_c.set_axis_off()

    # Track labels (left edge).
    ax_c.text(-1.0, 1.0, "child pat", ha="right", va="center",
              fontsize=9, color=COLOR_PAT, fontweight="bold")
    ax_c.text(-1.0, 0.0, "child mat", ha="right", va="center",
              fontsize=9, color=COLOR_MAT, fontweight="bold")

    # Backing lanes for the two tracks.
    for y_track, color in ((1.0, COLOR_PAT), (0.0, COLOR_MAT)):
        ax_c.add_patch(
            Rectangle(
                (-0.5, y_track - 0.32), PANEL_C_N, 0.64,
                facecolor=color, edgecolor="black",
                linewidth=0.4, alpha=0.18,
            )
        )

    for i, g in enumerate(pat_track):
        ax_c.text(i, 1.0, g, ha="center", va="center",
                  fontsize=10, family="monospace", fontweight="bold")
    for i, g in enumerate(mat_track):
        ax_c.text(i, 0.0, g, ha="center", va="center",
                  fontsize=10, family="monospace", fontweight="bold")

    # Annotation 1: CpG1 — compound genetic-epigenetic heterozygote.
    ax_c.add_patch(FancyArrowPatch(
        (PANEL_C_CPG1_IDX, -1.2), (PANEL_C_CPG1_IDX, -0.45),
        arrowstyle="->", mutation_scale=10, color="black", linewidth=0.8,
    ))
    ax_c.text(
        PANEL_C_CPG1_IDX, -1.4,
        "CpG1 — compound genetic-epigenetic heterozygote\n"
        "(methylation state co-segregates with SNV1 genotype)",
        ha="center", va="top", fontsize=8.5,
    )

    # Annotation 2: CpG2 — epimutation. Arrow + label above the paternal
    # track; the side-inset (below) carries the parent-vs-child comparison.
    ax_c.add_patch(FancyArrowPatch(
        (PANEL_C_CPG2_IDX, 2.0), (PANEL_C_CPG2_IDX, 1.45),
        arrowstyle="->", mutation_scale=10, color="black", linewidth=0.8,
    ))
    ax_c.text(
        PANEL_C_CPG2_IDX, 2.2,
        "CpG2 — epimutation\n(see inset →)",
        ha="center", va="bottom", fontsize=8.5, fontweight="bold",
    )

    ax_c.set_title(
        "Panel C — zoomed-out methylation profile across ~30 CpGs "
        "(paternal above maternal)",
        fontsize=11, pad=12,
    )

    # Dad-vs-child inset, sharing the same gridspec row but its own subplot
    # so its layout is not crammed inside Panel C's data range.
    ax_inset = fig.add_subplot(gs[2, 1])
    ax_inset.set_xlim(0, 1)
    ax_inset.set_ylim(0, 1)
    ax_inset.set_axis_off()
    ax_inset.add_patch(
        Rectangle(
            (0.04, 0.10), 0.92, 0.80,
            facecolor="white", edgecolor="black", linewidth=0.6,
            transform=ax_inset.transAxes,
        )
    )
    ax_inset.text(
        0.5, 0.84, "CpG2 — same physical homolog,\nparent vs child",
        ha="center", va="top", fontsize=10, fontweight="bold",
        transform=ax_inset.transAxes,
    )
    ax_inset.text(
        0.20, 0.55, "dad   pat:",
        ha="left", va="center", fontsize=10,
        family="monospace", color=COLOR_PAT,
        transform=ax_inset.transAxes,
    )
    ax_inset.text(
        0.62, 0.55, dad_pat_track[PANEL_C_CPG2_IDX],
        ha="center", va="center", fontsize=18,
        family="monospace", fontweight="bold",
        transform=ax_inset.transAxes,
    )
    ax_inset.text(
        0.20, 0.36, "child pat:",
        ha="left", va="center", fontsize=10,
        family="monospace", color=COLOR_PAT,
        transform=ax_inset.transAxes,
    )
    ax_inset.text(
        0.62, 0.36, pat_track[PANEL_C_CPG2_IDX],
        ha="center", va="center", fontsize=18,
        family="monospace", fontweight="bold",
        transform=ax_inset.transAxes,
    )
    ax_inset.text(
        0.5, 0.18,
        "Methylation gained on\nthis specific homolog\nin the meiosis to the child.",
        ha="center", va="center", fontsize=8.5, style="italic",
        transform=ax_inset.transAxes,
    )

    fig.suptitle(
        "Figure 2 — \"After\": phasing reveals epimutations and "
        "compound genetic-epigenetic heterozygotes",
        fontsize=13, y=0.985,
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=180)
    plt.close(fig)
    print(f"[wiki] Wrote {out_path}")


# --- Markdown -----------------------------------------------------------

MOTIVATION_MD = """\
# Why phase DNA methylation?

This page is part of the [tapestry wiki](../index.md). It motivates
the rest of the wiki by answering one question: *why is it worth
phasing per-CpG methylation onto each haplotype, instead of leaving it
as a single number per CpG?* Two cartoon figures take a small synthetic
locus, show what it looks like before phasing, then redraw the same
reads after phasing to make two biological phenomena visible.

The motivation does not depend on which phasing strategy gets you to
parental-haplotype resolution, so this page is shared between
tapestry's [pedigree-wise](../pedigree_wise_workflow/index.md) and
[trio-wise](../trio_wise_workflow/README.md) workflows.

## Definitions

- **Epimutation** — a change in the methylation state of a specific
  physical homolog across a single meiosis. Detectable only when a
  parent and child can be compared on the *same* haplotype, which in
  turn requires phased methylation.
- **Compound genetic-epigenetic heterozygote** — an individual who is
  simultaneously heterozygous at a SNV *and* heterozygous in
  methylation state at a nearby CpG, with the methylation state
  tracking the SNV genotype across the two haplotypes. Invisible to
  either an unphased genotype call or an unphased methylation call,
  but trivial to read off paired phased tracks.

## Figure 1 — before phasing

![Figure 1 — before](fig1_before_unphased.png)

A small synthetic locus with two SNVs (`SNV1`, `SNV2`) bracketing two
CpGs (`CpG1`, `CpG2`). Twelve reads span the whole locus. Each read
is annotated at the four marked positions: a `0` or `1` at each SNV
(REF/ALT bit, matching the convention used throughout the wiki and in
the vendored
[`inheritance_mapping/`](../pedigree_wise_workflow/inheritance_mapping/README.md)
section), and a filled (`●`) or open (`○`) circle at each CpG
indicating methylation status on that read.

In this toy, six of the twelve reads carry `(0, 0)` at the two SNVs
and the other six carry `(1, 1)` — informative phasing anchors that
the unphased pile-up is *not yet using*. The two-bar plot to the
right reports the pooled methylation level at each CpG: both come
out at 50 %, the least-informative possible value. A 50 % per-CpG
number is consistent with many biological truths — both haplotypes
at 50 %, one fully methylated and the other unmethylated, asymmetric
methylation between maternal and paternal homologs — and the
unphased pile-up cannot distinguish them.

## Figure 2 — after phasing

![Figure 2 — after](fig2_after_phased.png)

The same twelve reads, now redrawn under the assumption that phasing
has been done.

- **Panel A** regroups the reads by haplotype (paternal above
  maternal, with a faint divider) and recolours them. Both SNVs
  agree on the assignment, so phasing is robust against a single
  sequencing error at either site.
- **Panel B** replaces each of Figure 1's two pooled bars with two
  per-haplotype bars, drawn on the same 0–100 % y-axis. CpG1 comes
  out at 0 % paternal / 100 % maternal; CpG2 at 100 % paternal /
  0 % maternal. Each Figure 1 bar was hiding a maximally-far-apart
  pair of haplotype-level values, and the two CpGs point in
  *opposite* directions — an unphased aggregate erases both.
- **Panel C** zooms out across ~30 CpGs in a short genomic window.
  Most positions are concordant between the two haplotypes (both
  methylated, both unmethylated). Two positions diverge: CpG1, at
  which the haplotype-resolved methylation co-segregates with the
  SNV1 genotype (a *compound genetic-epigenetic heterozygote*), and
  CpG2, at which the child's paternal homolog is methylated but
  dad's same physical homolog is not (an *epimutation* — a
  methylation change on a specific physical homolog across one
  meiosis).

## What's next

The rest of the wiki is concerned with how tapestry actually performs
the phasing summarised by Figure 2:

- The [pedigree-wise workflow](../pedigree_wise_workflow/index.md)
  combines hiphase's read-backed phasing with `gtg-ped-map` /
  `gtg-concordance`'s inheritance-based phasing across a full
  pedigree, labelling each measurement with a founder haplotype.
- The [trio-wise workflow](../trio_wise_workflow/README.md) uses
  whatshap / pedMEC trio phasing to label each measurement with one
  of the parents' haplotypes — an option for the trio-only setting.

For a worked example of how to query tapestry's output for the two
phenomena above (epimutations, compound genetic-epigenetic
heterozygotes), see
[`trio_wise_workflow/output_format_trio/output_format_trio.md`](../trio_wise_workflow/output_format_trio/output_format_trio.md).
"""


def page_motivation(outdir: Path) -> None:
    page_dir = outdir / "motivation"
    page_dir.mkdir(parents=True, exist_ok=True)
    _render_fig1_before(page_dir / "fig1_before_unphased.png")
    _render_fig2_after(page_dir / "fig2_after_phased.png")
    md_path = page_dir / "motivation.md"
    md_path.write_text(MOTIVATION_MD)
    print(f"[wiki] Wrote {md_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

PAGES = {
    "motivation": page_motivation,
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--page", choices=sorted(PAGES.keys()),
        help="Render only one page (default: render every page).",
    )
    parser.add_argument(
        "--outdir", type=Path, default=WIKI_DIR,
        help="Directory to write the wiki into.",
    )
    args = parser.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    targets = [PAGES[args.page]] if args.page else list(PAGES.values())
    for fn in targets:
        fn(args.outdir)


if __name__ == "__main__":
    main()
